---
- name: Create VM Demo
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    create_vm_aws_vpc_subnet_name: "{{ aws_vpc_subnet_name }}"
    create_vm_aws_keypair_name: "{{ aws_keypair_name }}"
    create_vm_aws_securitygroup_name: "{{ aws_securitygroup_name }}"

  vars_files:
    - "vars/vm_blueprints/{{vm_blueprint}}.yml"
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - create_vm_aws_vpc_subnet_name is defined
          - create_vm_aws_keypair_name is defined
          - create_vm_aws_securitygroup_name is defined
        fail_msg: "Required variables not set"

    - name: Include create vm role
      ansible.builtin.include_role:
        name: create_vm
